# Generated by Django 5.2.3 on 2025-07-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_generation_user_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='generation',
            name='image_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
