# Generated by Django 5.2.3 on 2025-07-15 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0005_generationtemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generation',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='generation',
            name='template_type',
        ),
        migrations.RemoveField(
            model_name='generation',
            name='tone',
        ),
    ]
