# Generated by Django 5.2.3 on 2025-09-23 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0006_remove_generation_platform_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="generation",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Генерация",
                "verbose_name_plural": "Генерации",
            },
        ),
        migrations.AlterModelOptions(
            name="generationtemplate",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "Шаблон генерации",
                "verbose_name_plural": "Шаблоны генерации",
            },
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "verbose_name": "Профиль пользователя",
                "verbose_name_plural": "Профили пользователей",
            },
        ),
        migrations.AlterField(
            model_name="generation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="generation",
            name="image_url",
            field=models.CharField(
                blank=True,
                help_text="Множественные URL разделены символом |",
                max_length=512,
                null=True,
                verbose_name="URL изображения(й)",
            ),
        ),
        migrations.AlterField(
            model_name="generation",
            name="result",
            field=models.TextField(verbose_name="Сгенерированный текст"),
        ),
        migrations.AlterField(
            model_name="generation",
            name="topic",
            field=models.TextField(verbose_name="Тема"),
        ),
        migrations.AlterField(
            model_name="generation",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="generationtemplate",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="generationtemplate",
            name="is_default",
            field=models.BooleanField(default=False, verbose_name="По умолчанию"),
        ),
        migrations.AlterField(
            model_name="generationtemplate",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название шаблона"),
        ),
        migrations.AlterField(
            model_name="generationtemplate",
            name="settings",
            field=models.JSONField(
                help_text="JSON с параметрами генерации", verbose_name="Настройки"
            ),
        ),
        migrations.AlterField(
            model_name="generationtemplate",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="generationtemplate",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generation_templates",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatars/", verbose_name="Аватар"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(blank=True, verbose_name="О себе"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="city",
            field=models.CharField(blank=True, max_length=100, verbose_name="Город"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="Дата рождения"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="first_name",
            field=models.CharField(blank=True, max_length=50, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="last_name",
            field=models.CharField(blank=True, max_length=50, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=30, verbose_name="Телефон"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="terms_accepted",
            field=models.BooleanField(default=False, verbose_name="Принял условия"),
        ),
    ]
