# Generated by Django 5.2.3 on 2026-01-11 19:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0007_alter_generation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор токена доступа', unique=True, verbose_name='Токен')),
                ('token_type', models.CharField(choices=[('DEMO', 'Демо (5 дней, 5 ген./день)'), ('MONTHLY', '30 дней'), ('YEARLY', '365 дней')], max_length=10, verbose_name='Тип токена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('expires_at', models.DateTimeField(help_text='Токен становится недействительным после этой даты', verbose_name='Дата истечения')),
                ('daily_generations_left', models.IntegerField(default=0, help_text='Для DEMO: количество генераций доступных сегодня (обнуляется каждый день)', verbose_name='Осталось генераций сегодня')),
                ('generations_reset_date', models.DateField(blank=True, help_text='Дата последнего сброса счетчика генераций', null=True, verbose_name='Дата сброса счетчика')),
                ('total_used', models.IntegerField(default=0, help_text='Общее количество генераций через этот токен', verbose_name='Всего использований')),
                ('is_active', models.BooleanField(default=True, help_text='Неактивные токены не могут быть использованы', verbose_name='Активен')),
                ('last_used', models.DateTimeField(blank=True, help_text='Время последней генерации с этим токеном', null=True, verbose_name='Последнее использование')),
                ('current_ip', models.GenericIPAddressField(blank=True, help_text='IP адрес последнего использования (для технической диагностики)', null=True, verbose_name='Текущий IP')),
            ],
            options={
                'verbose_name': 'Временный токен доступа',
                'verbose_name_plural': 'Временные токены доступа',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='generator_t_token_aaac30_idx'), models.Index(fields=['is_active', 'expires_at'], name='generator_t_is_acti_7def0a_idx')],
            },
        ),
    ]
