# Generated by Django 5.2.3 on 2026-01-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0008_temporaryaccesstoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryaccesstoken',
            name='token_type',
            field=models.CharField(choices=[('DEMO', 'Демо (5 дней, 5 ген./день)'), ('MONTHLY', '30 дней'), ('YEARLY', '365 дней'), ('DEVELOPER', 'Разработчик (бессрочный, безлимит)')], max_length=10, verbose_name='Тип токена'),
        ),
    ]
