# Generated by Django 5.2.3 on 2026-02-08 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0017_add_telegram_user_id_to_tokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(verbose_name='Telegram User ID')),
                ('telegram_username', models.CharField(blank=True, max_length=100, null=True)),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='1-5 звёзд', null=True, verbose_name='Оценка')),
                ('moderation_status', models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрен'), ('rejected', 'Отклонён')], default='pending', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Опубликован')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(verbose_name='Telegram User ID')),
                ('telegram_username', models.CharField(blank=True, max_length=100, null=True)),
                ('telegram_chat_id', models.BigIntegerField(help_text='ID чата с пользователем (для пересылки сообщений)', verbose_name='ID приватного чата')),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('closed', 'Закрыт')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Чат поддержки',
                'verbose_name_plural': 'Чаты поддержки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(verbose_name='Telegram User ID')),
                ('telegram_username', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('in_progress', 'В работе'), ('resolved', 'Решён'), ('closed', 'Закрыт')], default='open', max_length=20)),
                ('source', models.CharField(default='bot', help_text='bot | group', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Тикет поддержки',
                'verbose_name_plural': 'Тикеты поддержки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['telegram_user_id'], name='generator_r_telegra_f570ea_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['moderation_status', 'created_at'], name='generator_r_moderat_cf4ffc_idx'),
        ),
        migrations.AddIndex(
            model_name='supportchat',
            index=models.Index(fields=['telegram_user_id'], name='generator_s_telegra_85c1b1_idx'),
        ),
        migrations.AddIndex(
            model_name='supportchat',
            index=models.Index(fields=['status'], name='generator_s_status_56c45a_idx'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='support_chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='generator.supportchat', verbose_name='Приватный чат'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['telegram_user_id'], name='generator_s_telegra_ada58f_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status', 'created_at'], name='generator_s_status_b55ce5_idx'),
        ),
    ]
