# Generated by Django 4.2 on 2026-10-06 20:36
#
# Только модель AccessEvent. Старый дрейф моделей и миграций (переименования
# индексов, telegram_user_id_hash, total_used) сюда намеренно не входит:
# по плану его закрывает отдельная миграция в фазе 3.

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0018_support_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('DEMO_TOKEN', 'Выдача демо-токена')], max_length=32, verbose_name='Тип события')),
                ('ip_hash', models.CharField(max_length=64, verbose_name='HMAC-хэш IP')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Событие доступа',
                'verbose_name_plural': 'События доступа',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='accessevent',
            index=models.Index(fields=['event_type', 'ip_hash', 'created_at'], name='generator_a_event_t_8eaec1_idx'),
        ),
        migrations.AddIndex(
            model_name='accessevent',
            index=models.Index(fields=['created_at'], name='generator_a_created_a9ff48_idx'),
        ),
    ]
